### ISSUE TITLE
Add support for F macro

### ISSUE THREAD

**Issue by sidey79** [end2endzone/win32Arduino#16]
Hi, is there any chance to get support of a F macro?

I think a macro without any functionality is enough
`#define F(V1) V1`

**Comment by end2endzone** [comment]
Good catch. I didn't think of this one. I even have other libraries which makes use of F() but still untested with win32Arduino. It will be added soon.

**Comment by end2endzone** [comment]
The implementation should also support `PROGMEM` keyword. The implementation should be located in the include file `avr/pgmspace.h` to allow statement of type `#include <avr/pgmspace.h>`.
